function r = classifyrate(Y,T)

% function C = confmat(Y,T)
% Creates the confusion matrix of a trained neural net.
% Y is the output matrix generated by sim(net,p) after a net has been trained.
% T is the matrix containg the target values.

N = size(Y,1); % number of classes (also number of rows and columns in confusion matrix)
M = size(Y,2); % number patterns to be classified
C = zeros(N,N); % initialize confusion matrix to zeros

% for each image in X compute average distance to each class prototypes
for k=1:M
   i = find(T(:,k)==1);
   J = find(Y(:,k)==max(Y(:,k)));
   j = J(1);
   C(i,j) = C(i,j) + 1;  
end
class_rate = 0;
for i=1:N
    class_rate = class_rate + C(i,i);
end
% disp(C);
class_rate = class_rate/M * 100;
r = class_rate;
%disp(['Classification Rate = ', num2str(class_rate), '%']);